/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.procureagent.service;import org.junit.jupiter.api.Test;import static org.assertj.core.api.Assertions.assertThat;/**
                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                     */
class SourcingRecommendationApprovalServiceTest{private final SourcingRecommendationApprovalService s=new SourcingRecommendationApprovalService();/**
                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                       */
@Test void awardsGovernedRecommendation(){var r=s.assess(new SourcingRecommendationApprovalService.Request("S1",true,true,true,true,true,true,true,3,10,true,true));assertThat(r.decision()).isEqualTo(SourcingRecommendationApprovalService.Decision.AWARD);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@Test void negotiatesPriceAndContract(){var r=s.assess(new SourcingRecommendationApprovalService.Request("S2",true,true,true,true,true,true,true,20,10,false,true));assertThat(r.actions()).hasSize(2);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@Test void blocksUnfairSourcing(){var r=s.assess(new SourcingRecommendationApprovalService.Request("S3",false,false,false,false,false,false,false,3,10,true,false));assertThat(r.blockers()).hasSize(8);}}
